<?php echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" ?>
<people>
	<?php if(count($this->people) > 0): ?>
        <?php foreach ($this->people as $person):
            ?>
                <person>
                    <id><?php echo $person['id']?></id>
                    <name><?php echo $person['name']?></name>
                    <age><?php echo $person['age']?></age>
                    <sex><?php echo $person['sex']?></sex>
                    <imageHash><?php echo $person['eTag']?></imageHash>
                </person>
            <?php endforeach;?>
        <?php
        endif;
        ?>        
</people>