<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
	<center>
		<?= $this->render('header.phtml') ?>

		<div id="content" style="width: 1000px;"><?= $this->layout()->content ?></div>

		<?= $this->render('footer.phtml') ?>
	</center>
</body>
</html>