<?php

/**
 * Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Message extends BaseMessage
{
	public static function getById($id) {
		$user  = Doctrine_Query::create()
             ->from('Message m')
             ->where('m.id= ?',$id)
             ->fetchOne();
        return $user;
	}
	
	public function setAsRead() {
		$this->readTimestamp = time();
		$this->save();		
	}
}