<?php

/**
 * Place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Place extends BasePlace
{
   public $distance;
   public static function getById($id) {
		$q  = Doctrine_Query::create()
             ->from('Place p')
             ->where('p.id= ?',$id);
		Logger::getSQLLogger()->info($q->getSqlQuery());
        $place = $q->fetchOne();
             
        return $place;
	}

   public static function getPlacesInArea($area){
       $query = Doctrine_Query::create()->from('Place p');
       if (isset($area['bottom_left']['lat'])) {
           $query->addWhere('p.latitude >= ?',$area['bottom_left']['lat']);
       }
       if (isset($area['top_left']['lat'])) {
           $query->addWhere('p.latitude <= ?',$area['top_left']['lat']);
       }
       if (isset($area['top_left']['long'])) {
           $query->addWhere('p.longitude >= ?',$area['top_left']['long']);
       }
       if (isset($area['top_right']['long'])) {
           $query->addWhere('p.longitude <= ?',$area['top_right']['long']);
       }
       Logger::getSQLLogger()->info($query->getSqlQuery());
       $places = $query->execute();

       return $places;
   }

   public function getAddressLine() {
        return $this->city_id . "," . $this->address;
   }

  public function getAll() {
        $q = Doctrine_Query::create()
          ->from('Place p');
        $rows = $q->fetchArray();

        return $rows;
  }
  public function deleteAll() {
      $q = Doctrine_Query::create() -> delete()
                                    -> from('Place');
      $q->execute();
  }
}
