<?php

/**
 * Place
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Placetype extends BasePlacetype
{
   public static function getById($id) {
		$q  = Doctrine_Query::create()
             ->from('Placetype p')
             ->where('p.id= ?',$id);
		Logger::getSQLLogger()->info($q->getSqlQuery());
        $place = $q->fetchOne();
             
        return $place;
	}

	public function getAll() {
		$q = Doctrine_Query::create()
			->from('Placetype p');
		$rows = $q->fetchArray();

		return $rows;
	}
}