<?php

/**
 * Setting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Setting extends BaseSetting
{
   public static function getByName($name) {
		$q  = Doctrine_Query::create()
             ->from('Setting s')
             ->where('s.name = ?', $name);
        $row = $q->fetchOne();
             
        return $row;
	}

	public function getAll() {
		$q = Doctrine_Query::create()
			->from('Setting s');
		$rows = $q->fetchArray();

		return $rows;
	}

	public function updateByName($name, $value) {
		$q = Doctrine_Query::create()->update('Setting s')
									->set('s.value', $value)
									->where('s.name = ?', $name);
		$rows = $q->fetchArray();

		return $rows;
	}
}